In [1]:
import numpy as np
a = np.array([[2,4],[0,4],[7,9],[3,7]])
b = np.array([[9,2],[4,1],[1,7],[0,2]])

In [2]:
a + b

array([[11,  6],
       [ 4,  5],
       [ 8, 16],
       [ 3,  9]])

In [3]:
c = np.array([[1,3,7],[2,9,0]])
c + b

ValueError: operands could not be broadcast together with shapes (2,3) (4,2) 

In [4]:
6 * c

array([[ 6, 18, 42],
       [12, 54,  0]])

In [5]:
d = np.array([[6,3],[0,1]])
d / 3

array([[2.        , 1.        ],
       [0.        , 0.33333333]])

In [6]:
import numpy as np
a = np.array([[2,5],[1,9],[0,3]])
b = np.array([[2],[3]])
np.dot(a,b) #行列の掛け算

array([[19],
       [29],
       [ 9]])

In [35]:
c = np.array([[1,4],[2,0],[8,1],[3,5]])
d = np.array([[1],[3]])
np.dot(c,d)

NameError: name 'np' is not defined

In [8]:
import numpy as np
a = np.array([[1,3],[6,1],[2,0]])
b = np.array([[0,2],[11,7]])
np.dot(a,b)

array([[33, 23],
       [11, 19],
       [ 0,  4]])

In [1]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [2]:
np.dot(b,a)

array([[23, 34],
       [31, 46]])

In [4]:
c = np.array([[2,1],[4,3]])
a.dot(b).dot(c)

array([[126,  85],
       [286, 193]])

In [7]:
eye = np.eye(2,dtype=int)
eye

array([[1, 0],
       [0, 1]])

In [8]:
np.dot(a,eye)

array([[1, 2],
       [3, 4]])

In [9]:
np.dot(eye,a)

array([[1, 2],
       [3, 4]])

In [10]:
a

array([[1, 2],
       [3, 4]])

In [11]:
import numpy as np
a = np.array([[2,5],[1,3]])
b = np.array([[3,-5],[-1,2]])
np.dot(a,b)

array([[1, 0],
       [0, 1]])

In [12]:
np.dot(b,a)

array([[1, 0],
       [0, 1]])

In [13]:
np.linalg.inv(a) #aの逆行列を求める


array([[ 3., -5.],
       [-1.,  2.]])

In [14]:
c = np.array([[3,1],[2,6],[4,5]])
c

array([[3, 1],
       [2, 6],
       [4, 5]])

In [15]:
c.T #cの転置行列

array([[3, 2, 4],
       [1, 6, 5]])

In [16]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [17]:
type(a)

numpy.ndarray

In [18]:
a.shape

(3,)

In [19]:
a.dtype

dtype('int32')

In [20]:
a[0]

1

In [21]:
a

array([1, 2, 3])

In [22]:
a[1]

2

In [24]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
b.shape

(2, 3)

In [26]:
b.dtype

dtype('int32')

In [28]:
b[0]

array([1, 2, 3])

In [29]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
b[1]

array([4, 5, 6])

In [31]:
b[0,0]

1

In [32]:
b[0][0]

1

In [33]:
b[1,2]

6

In [35]:
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
c.shape

(3, 4)

In [37]:
c[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
c[2:]

array([[ 9, 10, 11, 12]])

In [39]:
c[:2,1]

array([2, 6])

In [40]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [43]:
np.full((3,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [44]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [45]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
a + b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [49]:
a - b

array([[0, 0, 0],
       [0, 0, 0]])

In [50]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [51]:
a ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [52]:
a / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [53]:
a < 2

array([[ True, False, False],
       [False, False, False]])

In [55]:
array = np.array([1,2,3])
array

array([1, 2, 3])

In [56]:
list = [1,2,3]
list

[1, 2, 3]

In [57]:
list + [4]

[1, 2, 3, 4]

In [58]:
array + [4]

array([5, 6, 7])

In [59]:
list2 = []
for e in list:
    list2.append(e+4)
list2    

[5, 6, 7]

In [60]:
list

[1, 2, 3]

In [61]:
list*2

[1, 2, 3, 1, 2, 3]

In [62]:
array + 2

array([3, 4, 5])

In [63]:
array * 2

array([2, 4, 6])

In [64]:
list2 = []
for e in list:
    list2.append(e*2)
list2    

[2, 4, 6]

In [65]:
list

[1, 2, 3]

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2],[3,4]])
b = np.array([[6,7],[8,9]])


In [3]:
a

array([[1, 2],
       [3, 4]])

In [4]:
b

array([[6, 7],
       [8, 9]])

In [5]:
a * b

array([[ 6, 14],
       [24, 36]])

In [6]:
np.dot(a,b)

array([[22, 25],
       [50, 57]])

In [7]:
np.dot(b,a)

array([[27, 40],
       [35, 52]])

In [8]:
a.dot(b)

array([[22, 25],
       [50, 57]])

In [13]:
c = [[1,2],[3,4]]

In [10]:
c

[[1, 2], [[3, 4]]]

In [14]:
type(c)

list

In [15]:
c = np.array(c)

In [16]:
c

array([[1, 2],
       [3, 4]])

In [17]:
type(c)

numpy.ndarray

In [18]:
d = [[1,2,3,4,5],[2,3]]
d = np.array(d)
type(d)

numpy.ndarray

In [19]:
c = c.tolist()

In [20]:
c

[[1, 2], [3, 4]]

In [1]:
import numpy as np

In [2]:
np.random.rand(10) #0から1までの一様乱数

array([0.00621423, 0.46055577, 0.18605255, 0.16680279, 0.90967698,
       0.13411979, 0.186677  , 0.71118276, 0.68325352, 0.70434782])

In [3]:
np.random.rand(10,10)

array([[0.04600729, 0.30419594, 0.65531095, 0.09031873, 0.29908663,
        0.1157763 , 0.77771543, 0.11346201, 0.02895406, 0.4931765 ],
       [0.44381457, 0.24814523, 0.98244643, 0.08929493, 0.03231814,
        0.714825  , 0.01520059, 0.22602301, 0.70269046, 0.40926907],
       [0.23689522, 0.62438476, 0.80230492, 0.87014362, 0.35686497,
        0.001894  , 0.175462  , 0.03913057, 0.54254035, 0.13546823],
       [0.6896698 , 0.88559894, 0.78903913, 0.77539491, 0.4476653 ,
        0.27225933, 0.86319715, 0.11001022, 0.22803284, 0.09128594],
       [0.19423522, 0.28241633, 0.52579734, 0.61447954, 0.59421525,
        0.77124997, 0.56172169, 0.96032612, 0.77392586, 0.85516369],
       [0.38866948, 0.02977103, 0.65523039, 0.55917047, 0.82242224,
        0.58224749, 0.97368503, 0.55927186, 0.4615085 , 0.85756442],
       [0.8761095 , 0.52440769, 0.12842307, 0.91890937, 0.97215707,
        0.02892144, 0.59811777, 0.60326774, 0.19900648, 0.47500269],
       [0.48300597, 0.91392422, 0.8402480

In [4]:
a = np.random.rand(10,10)

In [6]:
a.shape

(10, 10)

In [7]:
np.random.randn(1) #標準正規分布　平均値=0 & 標準偏差=1の分布の乱数

array([-0.79012386])

In [9]:
randn5000 = np.random.randn(5000,5000)
randn5000.shape

(5000, 5000)

In [10]:
randn5000.mean()

-3.743959141738753e-05

In [11]:
 randn5000.std()

0.9998473140405792

In [12]:
np.random.randint(100)

88

In [13]:
np.random.randint(1,30,30)

array([24,  1,  8, 24, 19, 25,  3, 25, 29,  3, 15, 10, 16, 21, 27, 28, 14,
        3, 18, 21, 17, 21, 24,  8,  5, 15, 12, 17,  4,  7])

In [14]:
randint30 = np.random.randint(1,30,(30,30))

In [15]:
randint30

array([[25,  5,  1, 20, 16,  8,  7,  3, 19,  8, 27,  3, 15, 20,  2, 25,
         6, 16, 12, 13, 12, 21,  1,  1, 18, 18,  2,  4,  8, 14],
       [27, 18, 18, 24,  3, 20, 24, 25, 22, 19, 29, 18, 21,  3, 23,  7,
         5, 25, 20, 17,  1, 22, 20, 11, 14, 21, 12, 17, 23, 15],
       [14, 26, 17, 17,  8, 28, 26, 23, 29, 26,  1, 15, 14, 20,  7,  8,
         6, 27, 11, 25, 17,  2, 20, 17, 14,  8, 10, 25, 14,  5],
       [19,  8, 23, 14, 23,  9,  5, 29, 23, 25, 22, 10, 24, 22, 15, 13,
        26, 13, 11,  3, 24, 24, 14,  9,  6, 10,  9, 20,  3,  4],
       [25, 24, 16,  2,  2, 29, 11,  9,  1,  3, 27, 18,  3,  3, 10, 29,
        16, 15, 21, 28, 13, 11, 18, 27, 22, 22, 16, 11, 18,  2],
       [25, 18,  9, 27, 14, 21, 23, 10, 19, 16, 21, 14, 10, 15, 25, 28,
        17, 18, 14,  3, 29, 13, 25, 25,  8,  6, 25,  6, 19, 21],
       [ 2,  3,  6, 28, 18, 20, 18, 17, 23,  6,  6, 22, 29, 28, 29, 28,
         4, 23,  5, 11, 13, 25, 14, 29, 22, 22, 24, 23, 21,  3],
       [ 6, 10, 16,  8, 27, 26,  6,  4, 1

In [16]:
randint30.shape

(30, 30)

In [17]:
np.random.seed(100) #seedを固定すると毎回同じ乱数生成が可能
np.random.randn()

-1.7497654730546974

In [18]:
np.random.randn()

0.34268040332750216

In [20]:
np.random.randn()

1.153035802563644

In [21]:
np.random.randn()

-0.25243603652138985

In [22]:
np.random.seed(100)

In [23]:
np.random.randn()

-1.7497654730546974

In [24]:
import numpy as np

In [25]:
a = np.array([[2,5],[1,3]])

In [26]:
a

array([[2, 5],
       [1, 3]])

In [27]:
b = np.linalg.inv(a) #逆行列

In [28]:
b

array([[ 3., -5.],
       [-1.,  2.]])

In [29]:
np.dot(a,b)

array([[1., 0.],
       [0., 1.]])

In [30]:
c = np.array([[3,1],[2,6],[4,5]]) 

In [31]:
c

array([[3, 1],
       [2, 6],
       [4, 5]])

In [32]:
c.T  #転置行列

array([[3, 2, 4],
       [1, 6, 5]])

In [33]:
a

array([[2, 5],
       [1, 3]])

In [34]:
a.T

array([[2, 1],
       [5, 3]])

In [35]:
d = np.array([[1,0,0],[0,1,0],[0,0,1]])

In [36]:
d

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [37]:
np.diag(d) #対角成分の取得

array([1, 1, 1])

In [38]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [39]:
b = np.array([5,6,7,8])
b

array([5, 6, 7, 8])

In [41]:
np.inner(a,b) #内積

70

In [42]:
np.outer(a,b) #外積

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

In [43]:
import numpy as np

In [44]:
np.tan(45)

1.6197751905438615

In [49]:
rd = np.radians(45)

In [50]:
rd

0.7853981633974483

In [51]:
np.tan(rd)

0.9999999999999999

In [52]:
rd = np.radians(90)
rd

1.5707963267948966

In [53]:
np.sin(rd)

1.0

In [54]:
np.e

2.718281828459045

In [55]:
np.exp(2) #eの2乗

7.38905609893065

In [56]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [57]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [58]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [59]:
b = np.array([-5,-1,-1,0,10,15,-1,2])
b

array([-5, -1, -1,  0, 10, 15, -1,  2])

In [60]:
np.sign(b)

array([-1, -1, -1,  0,  1,  1, -1,  1])

In [61]:
c = np.random.randn(10)

In [62]:
c

array([ 0.3426804 ,  1.1530358 , -0.25243604,  0.98132079,  0.51421884,
        0.22117967, -1.07004333, -0.18949583,  0.25500144, -0.45802699])

In [65]:
np.rint(c)

array([ 0.,  1., -0.,  1.,  1.,  0., -1., -0.,  0., -0.])

In [66]:
c

array([ 0.3426804 ,  1.1530358 , -0.25243604,  0.98132079,  0.51421884,
        0.22117967, -1.07004333, -0.18949583,  0.25500144, -0.45802699])

In [67]:
np.modf(c)

(array([ 0.3426804 ,  0.1530358 , -0.25243604,  0.98132079,  0.51421884,
         0.22117967, -0.07004333, -0.18949583,  0.25500144, -0.45802699]),
 array([ 0.,  1., -0.,  0.,  0.,  0., -1., -0.,  0., -0.]))

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
body = np.array([[182,169,198,178,176],[81,59,87,72,79]])

In [4]:
body

array([[182, 169, 198, 178, 176],
       [ 81,  59,  87,  72,  79]])

In [5]:
df = pd.DataFrame(body)

In [6]:
df

0    1    2    3    4
0  182  169  198  178  176
1   81   59   87   72   79

In [7]:
type(body)

numpy.ndarray

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
df.columns = ["jun","taka","tetsu","ken","kazu"]

In [10]:
df

jun  taka  tetsu  ken  kazu
0  182   169    198  178   176
1   81    59     87   72    79

In [11]:
df.index = ["height","weight"]

In [12]:
df

jun  taka  tetsu  ken  kazu
height  182   169    198  178   176
weight   81    59     87   72    79

In [15]:
df = df.rename(columns={"jun":"hikari"})

In [16]:
df

hikari  taka  tetsu  ken  kazu
height     182   169    198  178   176
weight      81    59     87   72    79

In [17]:
import pandas as pd

In [19]:
df = pd.DataFrame(data=[["81","100","69","78","95"],["78","93","71","82","89"]],columns=["A","B","C","D","E"])

In [20]:
df

A    B   C   D   E
0  81  100  69  78  95
1  78   93  71  82  89

In [21]:
df.index = ["math","english"]

In [22]:
df

A    B   C   D   E
math     81  100  69  78  95
english  78   93  71  82  89

In [23]:
type(df)

pandas.core.frame.DataFrame

In [24]:
df.shape

(2, 5)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, math to english
Data columns (total 5 columns):
A    2 non-null object
B    2 non-null object
C    2 non-null object
D    2 non-null object
E    2 non-null object
dtypes: object(5)
memory usage: 96.0+ bytes


In [26]:
df

A    B   C   D   E
math     81  100  69  78  95
english  78   93  71  82  89

In [27]:
df = df.astype(int)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, math to english
Data columns (total 5 columns):
A    2 non-null int32
B    2 non-null int32
C    2 non-null int32
D    2 non-null int32
E    2 non-null int32
dtypes: int32(5)
memory usage: 56.0+ bytes


In [29]:
df.describe()

A           B          C          D          E
count   2.00000    2.000000   2.000000   2.000000   2.000000
mean   79.50000   96.500000  70.000000  80.000000  92.000000
std     2.12132    4.949747   1.414214   2.828427   4.242641
min    78.00000   93.000000  69.000000  78.000000  89.000000
25%    78.75000   94.750000  69.500000  79.000000  90.500000
50%    79.50000   96.500000  70.000000  80.000000  92.000000
75%    80.25000   98.250000  70.500000  81.000000  93.500000
max    81.00000  100.000000  71.000000  82.000000  95.000000

In [30]:
df

A    B   C   D   E
math     81  100  69  78  95
english  78   93  71  82  89

In [31]:
df["A"]

math       81
english    78
Name: A, dtype: int32

In [32]:
type(df["A"])

pandas.core.series.Series

In [33]:
df.A

math       81
english    78
Name: A, dtype: int32

In [34]:
df

A    B   C   D   E
math     81  100  69  78  95
english  78   93  71  82  89

In [35]:
df.A

math       81
english    78
Name: A, dtype: int32

In [36]:
df.loc[:,"A"]

math       81
english    78
Name: A, dtype: int32

In [38]:
df.loc["math",["A","C"]]

A    81
C    69
Name: math, dtype: int32

In [39]:
df

A    B   C   D   E
math     81  100  69  78  95
english  78   93  71  82  89

In [40]:
df.iloc[0]

A     81
B    100
C     69
D     78
E     95
Name: math, dtype: int32

In [41]:
df.iloc[1]

A    78
B    93
C    71
D    82
E    89
Name: english, dtype: int32

In [42]:
df.iloc[0,0]

81

In [ ]:
df.iloc[:,0:3]

In [44]:
df

A    B   C   D   E
math     81  100  69  78  95
english  78   93  71  82  89

In [ ]:
df.iloc[0,0:4]

In [2]:
import pandas as pd

In [6]:
df = pd.read_csv("C:\\Users\\keita\\Desktop\\002-1.csv")

In [7]:
df.head()

0.563823406  0.926037583  0.564529862
0     0.226930     0.774618     0.415330
1     0.993598     0.030036     0.210686
2     0.355566     0.824691     0.629814
3     0.784904     0.614295     0.127989
4     0.442514     0.163834     0.088494

In [8]:
df = pd.read_csv("C:\\Users\\keita\\Desktop\\002-1.csv",header=None)

In [9]:
df.head()

0         1         2
0  0.563823  0.926038  0.564530
1  0.226930  0.774618  0.415330
2  0.993598  0.030036  0.210686
3  0.355566  0.824691  0.629814
4  0.784904  0.614295  0.127989

In [10]:
type(df)

pandas.core.frame.DataFrame

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
0    100 non-null float64
1    100 non-null float64
2    100 non-null float64
dtypes: float64(3)
memory usage: 2.4 KB


In [12]:
df.describe()

0           1           2
count  100.000000  100.000000  100.000000
mean     0.460883    0.487668    0.507878
std      0.278284    0.306104    0.295137
min      0.008179    0.005217    0.012975
25%      0.221251    0.209450    0.202979
50%      0.428495    0.455401    0.548508
75%      0.700257    0.761196    0.808566
max      0.994047    0.999703    0.980560

In [15]:
df2 = pd.read_csv("C:\\Users\\keita\\Desktop\\002-2.csv")

In [16]:
df2.head()

Employee ID  Evaluation  Promotion Salary in JPY (Date:2001-2017)  Quit
0         565         0.1        1.0                            Low   1.0
1         141         0.1        0.0                            Low   1.0
2         786         0.6        1.0                            Low   0.0
3        1770         1.0        1.0                            Low   0.0
4         662         1.0        0.0                            Low   0.0

In [17]:
df2.shape

(201, 5)

In [18]:
df2.tail()

Employee ID  Evaluation  Promotion  \
196                                                596         0.2        0.0   
197                                               1729         0.1        0.0   
198                                               1137         1.0        1.0   
199                                                NaN         NaN        NaN   
200  All employees data is collected annonimously, ...         NaN        NaN   

    Salary in JPY (Date:2001-2017)  Quit  
196                            Mid   0.0  
197                            Mid   0.0  
198                            Mid   0.0  
199                            NaN   1.0  
200                            NaN   NaN

In [20]:
df2 = pd.read_csv("C:\\Users\\keita\\Desktop\\002-2.csv",skipfooter=2,engine="python")

In [21]:
df2.tail()

Employee ID  Evaluation  Promotion Salary in JPY (Date:2001-2017)  Quit
194          766         1.0          0                            Mid     1
195         2350         0.0          0                            Mid     1
196          596         0.2          0                            Mid     0
197         1729         0.1          0                            Mid     0
198         1137         1.0          1                            Mid     0

In [22]:
df2.head()

Employee ID  Evaluation  Promotion Salary in JPY (Date:2001-2017)  Quit
0          565         0.1          1                            Low     1
1          141         0.1          0                            Low     1
2          786         0.6          1                            Low     0
3         1770         1.0          1                            Low     0
4          662         1.0          0                            Low     0

In [23]:
df2.columns

Index(['Employee ID', 'Evaluation', 'Promotion',
       'Salary in JPY (Date:2001-2017)', 'Quit'],
      dtype='object')

In [24]:
df2.columns = ["ID","Evaluation","Promotion","Salary","Quit"]

In [25]:
df2.head()

ID  Evaluation  Promotion Salary  Quit
0   565         0.1          1    Low     1
1   141         0.1          0    Low     1
2   786         0.6          1    Low     0
3  1770         1.0          1    Low     0
4   662         1.0          0    Low     0

In [26]:
df2["Sex"] = "Male"

In [27]:
df2.head()

ID  Evaluation  Promotion Salary  Quit   Sex
0   565         0.1          1    Low     1  Male
1   141         0.1          0    Low     1  Male
2   786         0.6          1    Low     0  Male
3  1770         1.0          1    Low     0  Male
4   662         1.0          0    Low     0  Male

In [28]:
df2.head(20)

ID  Evaluation  Promotion Salary  Quit   Sex
0    565         0.1          1    Low     1  Male
1    141         0.1          0    Low     1  Male
2    786         0.6          1    Low     0  Male
3   1770         1.0          1    Low     0  Male
4    662         1.0          0    Low     0  Male
5   1674         0.8          1    Low     0  Male
6    828         0.9          1    Low     1  Male
7   2287         0.9          1    Low     0  Male
8   1743         0.5          0    Low     0  Male
9    988         0.6          0    Low     0  Male
10   273         0.8          0    Low     1  Male
11  1993         0.5          0    Low     1  Male
12  1252         0.9          1    Low     0  Male
13  1349         0.7          1    Low     0  Male
14   825         0.3          1    Low     0  Male
15   110         1.0          0    Low     0  Male
16  2020         0.5          0   High     0  Male
17  1672         0.4          1   High     1  Male
18   767         0.4          1   High     1  Male
19  2218         0.3          1   High     0  Male

In [29]:
df2.describe()

ID  Evaluation   Promotion        Quit
count   199.000000  199.000000  199.000000  199.000000
mean   1204.874372    0.474874    0.180905    0.547739
std     696.072589    0.322665    0.385910    0.498971
min       4.000000    0.000000    0.000000    0.000000
25%     601.500000    0.200000    0.000000    0.000000
50%    1146.000000    0.400000    0.000000    1.000000
75%    1839.500000    0.800000    0.000000    1.000000
max    2493.000000    1.000000    1.000000    1.000000

In [31]:
df2.corr()

ID  Evaluation  Promotion      Quit
ID          1.000000   -0.020596   0.119456 -0.118589
Evaluation -0.020596    1.000000   0.231375  0.029446
Promotion   0.119456    0.231375   1.000000 -0.228676
Quit       -0.118589    0.029446  -0.228676  1.000000

In [32]:
eva = df2.groupby("Evaluation")

In [33]:
type(eva)

pandas.core.groupby.groupby.DataFrameGroupBy

In [36]:
eva.mean()

ID  Promotion      Quit
Evaluation                                  
0.0         1306.666667   0.000000  0.555556
0.1         1189.466667   0.066667  0.666667
0.2         1102.656250   0.031250  0.718750
0.3         1296.157895   0.157895  0.368421
0.4         1265.230769   0.307692  0.307692
0.5         1390.692308   0.153846  0.153846
0.6         1343.294118   0.411765  0.235294
0.7         1128.300000   0.200000  0.400000
0.8          985.600000   0.333333  0.600000
0.9         1239.360000   0.280000  0.800000
1.0         1125.000000   0.187500  0.687500